load test.case

class ExceptionTest : Test.Case {
	const def testCatch(self) {
		try {
			raise 'test'
		} catch e {
			received = e
		}
		self.expectEqual('test', received)
	}

	const def testCatchFromGenerator(self) {
		try {
			a, b = def {
				yield (none)
				raise 'test'
			} ()
		} catch e {
			received = e
		}
		self.expectEqual('test', received)
	}
}
